#!/bin/bash

# Simple manual steps to regenerate Gemfile.lock files
# Run these commands manually in your terminal

echo "📋 Manual steps to regenerate Gemfile.lock files:"
echo ""
echo "1️⃣ First, install Ruby via Homebrew (if not already installed):"
echo "   brew install ruby"
echo ""
echo "2️⃣ Add Homebrew Ruby to your PATH:"
echo "   export PATH=\"/opt/homebrew/opt/ruby/bin:\$PATH\""
echo "   export PATH=\"/opt/homebrew/lib/ruby/gems/3.3.0/bin:\$PATH\""
echo ""
echo "3️⃣ Verify Ruby version (should be 3.x):"
echo "   ruby --version"
echo ""
echo "4️⃣ Install bundler:"
echo "   gem install bundler"
echo ""
echo "5️⃣ Regenerate iOS Gemfile.lock:"
echo "   cd ios/App"
echo "   rm -f Gemfile.lock"
echo "   bundle install"
echo "   cd ../.."
echo ""
echo "6️⃣ Regenerate Android Gemfile.lock:"
echo "   cd android"
echo "   rm -f Gemfile.lock"
echo "   bundle install"
echo "   cd .."
echo ""
echo "7️⃣ Verify both files have modern Bundler:"
echo "   tail -3 ios/App/Gemfile.lock"
echo "   tail -3 android/Gemfile.lock"
echo ""
echo "8️⃣ Commit and push:"
echo "   git add ios/App/Gemfile.lock android/Gemfile.lock"
echo "   git commit -m 'Update Gemfile.lock files to use modern Bundler'"
echo "   git push"
